2025-03-10 01:33:38,753 INFO    MainThread:12872 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2025-03-10 01:33:38,753 INFO    MainThread:12872 [wandb_setup.py:_flush():76] Configure stats pid to 12872
2025-03-10 01:33:38,753 INFO    MainThread:12872 [wandb_setup.py:_flush():76] Loading settings from C:\Users\D. Sai Mani Kumar\.config\wandb\settings
2025-03-10 01:33:38,753 INFO    MainThread:12872 [wandb_setup.py:_flush():76] Loading settings from c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\settings
2025-03-10 01:33:38,753 INFO    MainThread:12872 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'DL_Assignment_01', 'entity': 'da24m016-indian-institute-of-technology-madras', 'root_dir': 'c:\\Users\\D. Sai Mani Kumar\\Downloads\\DL\\da6401_assignment1', 'run_id': 'bnikepv3', 'sweep_param_path': 'c:\\Users\\D. Sai Mani Kumar\\Downloads\\DL\\da6401_assignment1\\wandb\\sweep-p3vgp2yq\\config-bnikepv3.yaml', 'sweep_id': 'p3vgp2yq'}
2025-03-10 01:33:38,754 INFO    MainThread:12872 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-03-10 01:33:38,754 INFO    MainThread:12872 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2025-03-10 01:33:38,755 INFO    MainThread:12872 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250310_013338-bnikepv3\logs\debug.log
2025-03-10 01:33:38,755 INFO    MainThread:12872 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250310_013338-bnikepv3\logs\debug-internal.log
2025-03-10 01:33:38,756 INFO    MainThread:12872 [wandb_init.py:init():564] calling init triggers
2025-03-10 01:33:38,756 INFO    MainThread:12872 [wandb_init.py:init():571] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 128, 'hidden_layers': 4, 'learning_rate': 0.0001, 'loss': 'mean_squared_error', 'optimiser': 'adam', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {}
2025-03-10 01:33:38,756 INFO    MainThread:12872 [wandb_init.py:init():614] starting backend
2025-03-10 01:33:38,757 INFO    MainThread:12872 [wandb_init.py:init():618] setting up manager
2025-03-10 01:33:38,781 INFO    MainThread:12872 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2025-03-10 01:33:38,796 INFO    MainThread:12872 [wandb_init.py:init():624] backend started and connected
2025-03-10 01:33:38,837 INFO    MainThread:12872 [wandb_run.py:_config_callback():1342] config_cb None None {'activation': 'tanh', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 128, 'hidden_layers': 4, 'learning_rate': 0.0001, 'loss': 'mean_squared_error', 'optimiser': 'adam', 'weight_decay': 0, 'weight_init': 'xavier'}
2025-03-10 01:33:38,839 INFO    MainThread:12872 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2025-03-10 01:33:38,839 INFO    MainThread:12872 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-03-10 01:33:38,840 INFO    MainThread:12872 [wandb_init.py:init():716] updated telemetry
2025-03-10 01:33:38,962 INFO    MainThread:12872 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2025-03-10 01:35:08,952 ERROR   MainThread:12872 [wandb_init.py:init():775] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2025-03-10 01:35:09,017 ERROR   MainThread:12872 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_init.py", line 1170, in init
    run = wi.init()
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
